version: "3"

services:
  ip_block:
    build: ./ip_block
    container_name: ip_block
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ip_block:/ip_block
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - manager
  redis:
    image: redis
    container_name: redis
    command:
      - redis-server
      - --databases
      - "300"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime:ro
