tags:
  - '[미티게이션 페이지] 방화벽 configuration api'
summary:
  - configuration total
responses:
  200:
    description: 미티게이션 페이지 방화벽 configuration 총개수 api
    schema:
      id: firewall_configuration_total
    examples:
      7
  400:
    description: 미티게이션 페이지 방화벽 configuration 총개수 api 실패
    schema:
      id: firewall_configuration_total failed
      examples:
        {
          "status": 400,
          "result": "Your request is failed",
          "message": "Bad request syntax or unsupported method",
        }

