tags:
  - '[미티게이션 페이지] 방화벽 configuration api'
parameters:
  - in: formData
    name: fw_id
    type: integer
    required: true

responses:
  200:
    description: 미티게이션 페이지 방화벽 configuration 삭제 api
    schema:
      id: firewall_configuration_delete
    examples:
      {
        "status": 200,
        "result": "Your request is successful",
        "message": "Request fulfilled, document follows",
        "data":
          [
            {
              "fw_name": "forti_사무실",
              "group_name": "G_Blocked_IP"
            },
            {
              "fw_name": "pa_경지팀",
              "group_name": "G_Blocked_IP"
            }
          ]
      }
  400:
    description: 미티게이션 페이지 방화벽 configuration 삭제 api 실패
    schema:
      id: firewall_configuration_delete failed
      examples:
        {
          "status": 400,
          "result": "Your request is failed",
          "message": "Bad request syntax or unsupported method",
        }

